name: bryk-io/govuln-scan
description: Low-noise and reliable Go vulnerabilities scan using the official database (https://vuln.go.dev).
author: bryk-io
branding:
  icon: shield
  color: orange
runs:
  using: docker
  image: Dockerfile
  entrypoint: "/bin/scan"
inputs:
  go-version:
    description: "Go version [1.18, 1.19, 1.20]"
    required: true
    default: "1.20"
